##  -*-  coding: utf-8; mode: ruby -*-  ##
##  vi: set ft=ruby

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  config.vm.provider "virtualbox" do |v|
    v.name   = "vagrant-box-ubuntu-pbspro"
    v.memory = "1024"

    v.customize [
      "modifyvm",           :id,
      "--cableconnected1",  "on",
      "--hwvirtex",         "on",
      "--nestedpaging",     "on",
      "--largepages",       "on",
      "--ioapic",           "on",
      "--pae",              "on",
      "--paravirtprovider", "kvm",
      "--uartmode1",        "disconnected",
    ]
  end

  config.vm.boot_timeout = 900

  config.vm.provision("root", type: "shell",
                      path: "provision.root.sh",
                      privileged: true)
  config.vm.synced_folder(".", "/vagrant", disabled: true)

end
